# Generated by Django 3.2.16 on 2022-12-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={},
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='auth_userinfo',
        ),
    ]
