# Generated by Django 3.2.16 on 2022-12-05 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='班级名称')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='课程名称')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(blank=True, max_length=64, null=True, verbose_name='学生地址')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='学生手机号')),
                ('email', models.EmailField(max_length=254, verbose_name='学生邮箱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='学生描述')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='学生姓名')),
                ('age', models.SmallIntegerField(default=18, verbose_name='学生年龄')),
                ('classes', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='orm2.classes')),
                ('course', models.ManyToManyField(db_constraint=False, db_table='db_student2course', to='orm2.Course')),
                ('student_detail', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='orm2.studentdetail')),
            ],
        ),
    ]
