# Generated by Django 3.2.16 on 2022-12-05 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classes',
            table='db_classes',
        ),
        migrations.AlterModelTable(
            name='course',
            table='db_course',
        ),
        migrations.AlterModelTable(
            name='student',
            table='db_student',
        ),
        migrations.AlterModelTable(
            name='studentdetail',
            table='db_student_detail',
        ),
    ]
