# Generated by Django 3.2.16 on 2022-12-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu',
            name='name',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='姓名'),
        ),
    ]
