# Generated by Django 3.2.16 on 2022-12-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_alter_stu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu',
            name='chinese_score',
            field=models.SmallIntegerField(default=80, verbose_name='语文成绩'),
        ),
        migrations.AddField(
            model_name='stu',
            name='math_score',
            field=models.SmallIntegerField(default=80, verbose_name='数学成绩'),
        ),
    ]
